---
title: "Outcome Inequalty by Race in Early Stage High Grade Serous Ovarian Cancer"
author: "Kevin Kremer"
date: "10/8/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(SEER2R)
library(zoo)
library(survival)
library(survminer)
library(kableExtra)
library(RColorBrewer)

#Read SEER case files for ovarian cancer from 2004-2016 into data.frame
ovary.df <- read.SeerStat("ovcase_2004-2016.dic", UseVarLabelsInData = TRUE)

#Change data.frame to tibble
ovary.tib <- as_tibble(ovary.df)

#Rename columns
ovary.tib = rename(ovary.tib,
            Race = "Race_and_origin_recode_NHW_NHB_NHAIAN_NHAPI_Hispanic",
            Histo = "Histologic_Type_ICDO3",
            Lat = "Laterality",
            Summ_Stage = "SEER_Combined_Summary_Stage_2000_2004",
            Stage_Group = "Derived_AJCC_Stage_Group_6th_ed_20042015",
            T_Stage = "Derived_AJCC_T_6th_ed_20042015",
            N_Stage = "Derived_AJCC_N_6th_ed_20042015",
            M_Stage = "Derived_AJCC_M_6th_ed_20042015",
            Nodes_Ex = "Regional_nodes_examined_1988",
            Nodes_Pos = "Regional_nodes_positive_1988",
            Chemo = "Chemotherapy_recode_yes_no/unk",
            DiagYear = "Year_of_diagnosis",
            SurvMonths = "Survival_months",
            COD = "SEER_causespecific_death_classification",
            DiagAge = "Age_at_diagnosis",
            CutoffStatus = "Vital_status_recode_study_cutoff_used",
            DiagMonth = "Month_of_diagnosis_recode",
            CutoffStatus2 = "End_Calc_Vital_Status_Adjusted",
            MonthsFollowed = "Number_of_Intervals_Calculated")

#Remove columns
ovary.tib = select(ovary.tib, -c(Summary_stage_2000_1998, Sex, County, CutoffStatus2, Begin_Calc_Age_Adjusted))

#Change Grades to numeric values
ovary.tib$Grade <- ifelse(ovary.tib$Grade == "Poorly differentiated; Grade III", 3,
        ifelse(ovary.tib$Grade == "Moderately differentiated; Grade II", 2, 
        ifelse(ovary.tib$Grade == "Well differentiated; Grade I", 1,
        ifelse(ovary.tib$Grade == "Undifferentiated; anaplastic; Grade IV", 4, "Unk"))))

#Change Lat to Right/Left/Bil
ovary.tib$Lat <- ifelse(ovary.tib$Lat == "Right - origin of primary", "R",
        ifelse(ovary.tib$Lat == "Left - origin of primary", "L", 
        ifelse(ovary.tib$Lat == "Bilateral, single primary", "Bil", "Unk")))

#Change Race to manageable names
ovary.tib$Race <- ifelse(ovary.tib$Race == "Hispanic (All Races)", "Hisp",
        ifelse(ovary.tib$Race == "Non-Hispanic Asian or Pacific Islander", "API",
        ifelse(ovary.tib$Race == "Non-Hispanic American Indian/Alaska Native", "Native",
        ifelse(ovary.tib$Race == "Non-Hispanic Black", "Black",
        ifelse(ovary.tib$Race == "Non-Hispanic White", "White", "Unk")))))

#Change Nodes_Ex to None, Inadequate, Adequate
ovary.tib$Nodes_Ex <- ifelse(ovary.tib$Nodes_Ex == 0, "None",
        ifelse(ovary.tib$Nodes_Ex > 0 & ovary.tib$Nodes_Ex < 10, "Inadequate", "Adequate"))

#Change Nodes_Pos to Yes/No
ovary.tib$Nodes_Pos <- ifelse(ovary.tib$Nodes_Pos == 0, "No",
                    ifelse(ovary.tib$Nodes_Pos == 98, "Unk", "Yes"))

#Change COD variable to Alive(0) or Dead(1)
ovary.tib$COD <- ifelse(ovary.tib$COD == "Alive or dead of other cause", 0, 1)

#Filter out HGSOC and add column for race and age groups
serous <- filter(ovary.tib, Histo == "441" | Histo == "460" | Histo == "461" )
HGS <- filter(serous, Grade == 3 | Grade == 4)
HGS = mutate(HGS, Black.Race = ifelse(HGS$Race == "Black", "yes", "no") )
HGS = mutate(HGS, Race.Group = ifelse(HGS$Race == "Black", "Black",
                                      ifelse(HGS$Race == "White", "White","Other")))
HGS = mutate(HGS, TNM.Stage = ifelse(Nodes_Pos == "No" & M_Stage == "M0", "T1N0M0",
                                     ifelse(Nodes_Pos == "Unk" & M_Stage == "M0", "T1NxM0",
                                            ifelse(Nodes_Pos == "Yes" & M_Stage == "M0", "T1N1M0", "Any M1"))))
HGS.White.Black <- filter(HGS, HGS$Race == "Black" | HGS$Race == "White")
HGS$Age.Group <- cut(HGS$DiagAge, breaks = c(18, 30, 40, 50, 60 ,70, 80, 120), labels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+"), right = FALSE)
HGS.ES <- filter(HGS,(Nodes_Pos == "No" | Nodes_Pos == "Unk") & M_Stage == "M0" & Race != "Unk")
HGS.N0 <- filter(HGS, Nodes_Pos == "No" & M_Stage == "M0")
HGS.Nx <- filter (HGS, Nodes_Pos == "Unk" & M_Stage == "M0")
HGS.late <- filter (HGS, Nodes_Pos == "Yes" & M_Stage == "M0")
HGS.mets <- filter(HGS, M_Stage == "M1")
HGS.ES.WB <- filter(HGS.ES, Race == "Black" | Race == "White")
HGS.ES.HB <- filter(HGS.ES, Race == "Black" | Race == "Hisp")
```

# Survival of early-stage HGSOC by race

```{r, echo = FALSE}
HGS.ES$Race <- factor(HGS.ES$Race, levels = c('White', 'Black', 'Hisp', 'API', 'Native'))
fit.byRace <- survfit(Surv(SurvMonths, COD) ~ Race, HGS.ES)
ggsurvplot(fit.byRace, HGS.ES, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Race", title = "Survival of early stage HGSOC patients stratified by Race", legend.labs = c("White", "Black", "Any Hispanic", "Asian/Pacific Islander", "Native American"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
pairwise_survdiff(Surv(SurvMonths, COD) ~ Race, HGS.ES, rho = 0)
HGS.ES.Racetbl <- table(HGS.ES$Race)
kbl(HGS.ES.Racetbl, col.names = c("Race", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

# Comparing Black Race to All Other Races Combined

```{r, echo = FALSE}
fit.byBlack.Race <- survfit(Surv(SurvMonths, COD) ~ Black.Race, HGS.ES)
ggsurvplot(fit.byBlack.Race, HGS.ES, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Race", title = "Survival of early stage HGSOC patients stratified by Race", legend.labs = c("Other", "Black"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.Black.Racetbl <- table(HGS.ES$Black.Race)
kbl(HGS.ES.Black.Racetbl, col.names = c("Race", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.Black.Race <- coxph(Surv(SurvMonths, COD) ~ Black.Race, HGS.ES)
ggforest(ph.Black.Race, HGS.ES)
summary(ph.Black.Race)
```

# Comparing Black Race to White Race

```{r, echo = FALSE}
HGS.ES.WB$Race <- factor(HGS.ES.WB$Race, levels = c('White', 'Black'))
fit.byWB <- survfit(Surv(SurvMonths, COD) ~ Race, HGS.ES.WB)
ggsurvplot(fit.byWB, HGS.ES.WB, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Race", title = "Survival of early stage HGSOC patients stratified by Race", legend.labs = c("White", "Black"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.WBtbl <- table(HGS.ES.WB$Race)
kbl(HGS.ES.WBtbl, col.names = c("Race", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.WB <- coxph(Surv(SurvMonths, COD) ~ Race, HGS.ES.WB)
ggforest(ph.WB, HGS.ES.WB)
summary(ph.WB)
```

# Comparing Black Race to Hispanic Race

```{r, echo = FALSE}
HGS.ES.HB$Race <- factor(HGS.ES.HB$Race, levels = c('Hisp', 'Black'))
fit.byHB <- survfit(Surv(SurvMonths, COD) ~ Race, HGS.ES.HB)
ggsurvplot(fit.byHB, HGS.ES.HB, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Race", title = "Survival of early stage HGSOC patients stratified by Race", legend.labs = c("Any Hispanic", "Black"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.HBtbl <- table(HGS.ES.HB$Race)
kbl(HGS.ES.HBtbl, col.names = c("Race", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.HB <- coxph(Surv(SurvMonths, COD) ~ Race, HGS.ES.HB)
ggforest(ph.HB, HGS.ES.HB)
summary(ph.HB)
```

# Does use of chemotherapy change outcomes in different races?

## Black Race

```{r, echo = FALSE}
HGS.ES.Black.Chemo = filter(HGS.ES, Race == "Black" & Chemo == "Yes")
fit.Black.Chemo = survfit(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.Black.Chemo)
ggsurvplot(fit.Black.Chemo, HGS.ES.Black.Chemo, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Stage", title = "Survival of Black early stage HGSOC patients that \nreceived chemotherapy stratified by Stage", legend.labs = c("T1N0M0", "T1NxM0"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.Black.Chemotbl <- table(HGS.ES.Black.Chemo$Nodes_Pos)
kbl(HGS.ES.Black.Chemotbl, col.names = c("Positive Nodes", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.Black.Chemo <- coxph(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.Black.Chemo)
ggforest(ph.Black.Chemo, HGS.ES.Black.Chemo)
summary(ph.Black.Chemo)
```

## White Race

```{r, echo = FALSE}
HGS.ES.White.Chemo = filter(HGS.ES, Race == "White" & Chemo == "Yes")
fit.White.Chemo = survfit(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.White.Chemo)
ggsurvplot(fit.White.Chemo, HGS.ES.White.Chemo, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Stage", title = "Survival of White early stage HGSOC patients that \nreceived chemotherapy stratified by Stage", legend.labs = c("T1N0M0", "T1NxM0"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.White.Chemotbl <- table(HGS.ES.White.Chemo$Nodes_Pos)
kbl(HGS.ES.White.Chemotbl, col.names = c("Positive Nodes", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.White.Chemo <- coxph(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.White.Chemo)
ggforest(ph.White.Chemo, HGS.ES.White.Chemo)
summary(ph.White.Chemo)
```

## Hispanic Race

```{r, echo = FALSE}
HGS.ES.Hisp.Chemo = filter(HGS.ES, Race == "Hisp" & Chemo == "Yes")
fit.Hisp.Chemo = survfit(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.Hisp.Chemo)
ggsurvplot(fit.Hisp.Chemo, HGS.ES.Hisp.Chemo, pval = TRUE, xlab = "Months", break.time.by = 12, break.y.by = 0.1, legend.title = "Stage", title = "Survival of Hispanic early stage HGSOC patients that \nreceived chemotherapy stratified by Stage", legend.labs = c("T1N0M0", "T1NxM0"), legend = "bottom", palette = "Set1", ggtheme = theme_gray())
HGS.ES.Hisp.Chemotbl <- table(HGS.ES.Hisp.Chemo$Nodes_Pos)
kbl(HGS.ES.Hisp.Chemotbl, col.names = c("Positive Nodes", "Count")) %>% 
        kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
```{r, echo = FALSE}
ph.Hisp.Chemo <- coxph(Surv(SurvMonths, COD) ~ Nodes_Pos, HGS.ES.Hisp.Chemo)
ggforest(ph.Hisp.Chemo, HGS.ES.Hisp.Chemo)
summary(ph.Hisp.Chemo)
```